# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************
apiVersion: jumpstarter.dev/v1alpha1
kind: ExporterConfig
# endpoint and token are intentionally left empty
metadata:
  namespace: default
  name: qemu-demo
endpoint: ""
token: ""
export:
  qemu:
    type: jumpstarter_driver_qemu.driver.Qemu
    config:
      cpu: host 
      smp: 4
      mem: "8G" 
      default_partitions:
        # ubuntu
        OVMF_CODE.fd: /usr/share/OVMF/OVMF_CODE_4M.fd
        OVMF_VARS.fd: /usr/share/OVMF/OVMF_VARS_4M.fd
      hostfwd:
        ssh:
          hostport: 2222
          guestport: 22
