# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************
name: "AutoSD: Build and Publish"

on:
  pull_request:
    paths:
      - autosd/**
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        platform: [x86_64, aarch64]
        include:
          - platform: x86_64
            runner: ubuntu-latest
          - platform: aarch64
            runner: ubuntu-24.04-arm
    
    runs-on: ${{ matrix.runner }}

    defaults:
      run:
        working-directory: autosd

    steps:
      - uses: actions/checkout@v4

      - name: Install Base Dependencies
        run: |
          sudo apt update -y
          sudo apt install -y podman tree

      - name: Install AIB container script
        run: |
          wget -O auto-image-builder.sh \
          https://gitlab.com/CentOS/automotive/src/automotive-image-builder/-/raw/main/auto-image-builder.sh?ref_type=heads

          chmod +x auto-image-builder.sh

      - name: Prepare Build
        run: |
          mkdir -p $PWD/_build/containers-storage
          mkdir -p $PWD/_build/outputs

      - name: Build QEMU Images
        run: |
          export AIB_LOCAL_CONTAINER_STORAGE=$PWD/_build/containers-storage
          export AIB_BIN=./auto-image-builder.sh

          sudo -E bash ./scripts/build.sh

      - name: Build RPI4 Images
        run: |
          export AIB_LOCAL_CONTAINER_STORAGE=$PWD/_build/containers-storage
          export AIB_BIN=./auto-image-builder.sh
          export AIB_OCI_IMAGE=localhost/score:latest-rpi4
          export AIB_TARGET=rpi4

          sudo -E bash ./scripts/build.sh
        if: matrix.platform == 'aarch64'

      - name: Create QEMU Disk Images
        run: |
          export AIB_LOCAL_CONTAINER_STORAGE=$PWD/_build/containers-storage
          export AIB_BIN=./auto-image-builder.sh

          sudo -E bash ./scripts/save.sh

      - name: Create RPI4 Disk Images
        run: |
          export AIB_LOCAL_CONTAINER_STORAGE=$PWD/_build/containers-storage
          export AIB_BIN=./auto-image-builder.sh
          export AIB_OCI_IMAGE=localhost/score:latest-rpi4
          export AIB_TARGET=rpi4

          sudo -E bash ./scripts/save.sh

      - name: Inspect outputs directory
        run: |
         ls -la $PWD/_build/outputs

      - name: Upload QEMU Disk Image
        uses: actions/upload-artifact@v4
        with:
          name: score-autosd-${{ matrix.platform }}-latest.qcow2
          path: autosd/_build/outputs/score-autosd-${{ matrix.platform }}-latest.qcow2

      - name: Upload QEMU Container Image
        uses: actions/upload-artifact@v4
        with:
          name: score-autosd-${{ matrix.platform }}-latest-qemu.tar
          path: autosd/_build/outputs/score-autosd-${{ matrix.platform }}-latest-qemu.tar

      - name: Upload RPI4 Disk Image
        uses: actions/upload-artifact@v4
        with:
          name: score-autosd-${{ matrix.platform }}-latest.img
          path: autosd/_build/outputs/score-autosd-${{ matrix.platform }}-latest.img
        if: matrix.platform == 'aarch64'

      - name: Upload RPI4 Container Image
        uses: actions/upload-artifact@v4
        with:
          name: score-autosd-${{ matrix.platform }}-latest-rpi4.tar
          path: autosd/_build/outputs/score-autosd-${{ matrix.platform }}-latest-rpi4.tar
        if: matrix.platform == 'aarch64'
