# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************
name: "AutoSD: Build and Publish"

on:
  pull_request:
    paths:
      - autosd/**
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        platform: [qemu-x86_64, qemu-aarch64, rpi4-aarch64]
        include:
          - platform: qemu-x86_64
            runner: ubuntu-latest
            arch: x86_64
            target: qemu
            disk_format: qcow2
          - platform: qemu-aarch64
            runner: ubuntu-24.04-arm
            arch: aarch64
            target: qemu
            disk_format: qcow2
          - platform: rpi4-aarch64
            runner: ubuntu-24.04-arm
            arch: aarch64
            target: rpi4
            disk_format: img
    
    runs-on: ${{ matrix.runner }}

    env:
      AIB_BIN: ./auto-image-builder.sh
      AIB_OCI_IMAGE: localhost/score-autosd-${{ matrix.target }}:latest-${{ matrix.arch }}
      AIB_OCI_IMAGE_BUILDER: localhost/score-builder-${{ matrix.target }}:latest-${{ matrix.arch }}
      AIB_TARGET: ${{ matrix.target }}
      AIB_LOCAL_CONTAINER_STORAGE: ${{ github.workspace }}/autosd/_build/containers-storage

    defaults:
      run:
        working-directory: autosd

    steps:
      - uses: actions/checkout@v4

      - name: Install Base Dependencies
        run: |
          sudo apt update -y
          sudo apt install -y podman tree

      - name: Podman Info
        run: podman info

      - name: Install AIB container script
        run: |
          wget -O auto-image-builder.sh \
          https://gitlab.com/CentOS/automotive/src/automotive-image-builder/-/raw/main/auto-image-builder.sh?ref_type=heads

          chmod +x auto-image-builder.sh

      - name: Prepare Build
        run: |
          mkdir -p $PWD/_build/containers-storage
          mkdir -p $PWD/_build/outputs

      - name: Build Image
        run: sudo -E bash ./scripts/build.sh

      - name: Create Disk Images
        run: sudo -E bash ./scripts/save.sh
      
      - name: Inspect outputs directory
        run: ls -la $PWD/_build/outputs

      - name: Upload Disk Image
        uses: actions/upload-artifact@v4
        with:
          name: score-autosd-${{ matrix.target }}-${{ matrix.arch }}-latest.${{ matrix.disk_format }}
          path: autosd/_build/outputs/score-autosd-${{ matrix.target }}-${{ matrix.arch }}-latest.${{ matrix.disk_format }}

      - name: Upload Container Image
        uses: actions/upload-artifact@v4
        with:
          name: score-autosd-${{ matrix.target }}-${{ matrix.arch }}-latest.tar
          path: autosd/_build/outputs/score-autosd-${{ matrix.target }}-${{ matrix.arch }}-latest.tar

      - name: Upload Container Builder Image
        uses: actions/upload-artifact@v4
        with:
          name: score-autosd-builder-${{ matrix.target }}-${{ matrix.arch }}-latest.tar
          path: autosd/_build/outputs/score-autosd-builder-${{ matrix.target }}-${{ matrix.arch }}-latest.tar

      - name: Push Container Images
        run: |
          if [ "$(arch)" = "x86_64" ]; then
            OCI_ARCH=amd64
          else
            OCI_ARCH=arm64
          fi

          export IMG_NAMESPACE=${{ github.repository_owner }}/score-autosd-bootc
          export IMG_TAG=pr-${{ github.event.pull_request.number }}-$(git rev-parse --short HEAD)-${{ matrix.target }}-$OCI_ARCH
          export OCI_IMG=ghcr.io/$IMG_NAMESPACE:$IMG_TAG
          export OCI_IMG_TAR=_build/outputs/score-autosd-${{ matrix.target }}-${{ matrix.arch }}-latest.tar

          podman image import $OCI_IMG_TAR $OCI_IMG

          echo "${{ secrets.GITHUB_TOKEN }}" | podman login ghcr.io -u ${{ github.actor }} --password-stdin

          podman push $OCI_IMG
