# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************
name: "AutoSD: Build and Publish"

on:
  pull_request:
    paths:
      - autosd/**
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        platform: [amd64]
        include:
          - platform: amd64
            runner: ubuntu-24.04
    
    runs-on: ${{ matrix.runner }}

    permissions:
     contents: read
     packages: write
     id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@0.18.0

      - name: Install Base Dependencies
        run: |
          sudo apt update -y
          sudo apt install -y tree

      - name: Podman Info
        run: podman info

      - name: Build Image
        run: |
          bazel run //autosd:image

      - name: Check loaded image
        run: docker images

      - name: Test image content
        run: |
          echo '---/etc/containers/systemd/qm.container.d/10-lola-ipc.conf---'
          docker run --rm localhost/score-autosd10-qemu:latest-base /bin/bash -c 'cat /etc/containers/systemd/qm.container.d/10-lola-ipc.conf'

          echo '---/usr/lib/tmpfiles.d/lola_disc.conf---'
          docker run --rm localhost/score-autosd10-qemu:latest-base /bin/bash -c 'cat /usr/lib/tmpfiles.d/lola_disc.conf'

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Images
        if: github.event_name != 'pull_request'
        env:
          OCI_ORG: ${{ github.repository_owner }}
        run: |
          docker tag localhost/score-autosd10-qemu:latest-base ghcr.io/$OCI_ORG/score-autosd10-qemu:latest-base
          docker push ghcr.io/$OCI_ORG/score-autosd10-qemu:latest-base
       
